// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"context"
	"github.com/hashicorp/vault/api"
	"github.com/puppetlabs/leg/k8sutil/pkg/test/controller/fake"
	"github.com/puppetlabs/leg/vaultutil/pkg/vault"
)

// Injectors from wire.go:

func NewTestVaultSystemManager(ctx context.Context, cfg *vault.VaultConfig, vaultClient *api.Client) (*vault.VaultSystemManager, func(), error) {
	client := fake.NewClient()
	vaultSystemManager := vault.NewVaultSystemManager(vaultClient, client, cfg)
	return vaultSystemManager, func() {
	}, nil
}

func NewTestVaultInitializationManager(ctx context.Context, cfg *vault.VaultConfig, vaultClient *api.Client) (*vault.VaultInitializationManager, func(), error) {
	client := fake.NewClient()
	vaultSystemManager := vault.NewVaultSystemManager(vaultClient, client, cfg)
	vaultInitializationManager := vault.NewVaultInitializationManager(vaultSystemManager, cfg)
	return vaultInitializationManager, func() {
	}, nil
}
