#!/bin/bash
set -euo pipefail

#relay_go_test_args=( -race )

if ! command -v gotestsum >/dev/null 2>&1; then
  relay_go_test_command=( go test "${relay_go_test_args[@]}" ./... )
else
  relay_go_test_command=( gotestsum -f testname --no-summary output --rerun-fails --packages ./... -- "${relay_go_test_args[@]}" )
fi

while read -r relay_leg_moddir; do
  echo "test: ${relay_leg_moddir#./}"
  (
    cd "${relay_leg_moddir}"
    set -x
    exec "${relay_go_test_command[@]}"
  )
done < <( find . -mindepth 2 -name go.mod -printf '%h\n' )
